---
title: "**Overview**"
output:
  html_document: 
    toc: true
    toc_float: true
---

## **Motivation**

Wildfire hazards are considered as national threats. On average, more than 700 wildfires occur, over 7 million acres of land are burned down and 26,000 structures are destroyed annually, resulting in substantial economic and environmental losses with a number of fatalities and injuries. Considering the massive and devastating impacts of wildfires on human communities and the ecosystem, we decide to investigate wildfire trends available from our dataset in the hope of understanding how to better prevent and control wildfires. 

## **Data**

* 1.88 Million US Wildfires. 24 years of geo-referenced wildfire records   [here](https://www.kaggle.com/rtatman/188-million-us-wildfires)

* NOAA Weather Data

* `state` and `county` datasets in package `ggplot2`

* `state.x77` dataset

## **Initial Questions**

* The frequency of wildfire across location and time

* The top cause of wildfire in the U.S. over ten years

* Is there a relationship between size and duration of wildfires?

* Is there a relationship between temperature and the number of fires?

## **Main results**
In general, the number of wildfires in the U.S. from 2005 to 2015 is decreasing. Wildfires are more likely to happen from February to August. Texas had the highest number of wildfires during 2005 - 2015, while surprisingly, New York had the highest number of wildfires per square mile. The latter one should be more interesting because they will allow us to more directly compare wildfire across states. Plus, we find the most common cause to be debris burning. For wildfires with the highest burning size, they also have the longest duration. 

There is a significant association between size of wildfires and its duration together with causes. Fires that are caused by lightening tend to affect a larger area on average adjusted for duration.

We also build a simple linear regression model on the monthly number of fires and averaged monthly temperature. For every 1°C increase in monthly mean temperature, the total number of fires per month will increase by 3.820 on average.

## **Conclusion**
We recognize that wildfires have various causes and the severity (size, duration, etc.) of wildfires differ by a number of factors; thus, the final result that we present here may not be as accurate and comprehensive as we hoped it to be. Furthermore, as climate change continues to intensify wildfires, it is everyone's responsibility to understand and learn how to prevent wildfires from happening and protect nature and ourselves. In light of the above, we shall continue our quest to correctly and timely predict future wildfires, using extensive datasets with advanced predictive modeling techniques. 
