---
title: "**Report**"
author: "Sitong Cui, Jiarui Fu, Mengyuan Li, Mengyu Zhang, Ziqi Zhou"
date: "12/3/2019"
output:
  html_document: 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Motivation**
Wildfire hazards are considered as national threats, which can devour everything in its path, trees, homes and even lives, and spread for miles within a few minutes. The disastrous aftermath of the deadly wildfires, including their long-lasting threats to human health and the ecosystem, is also very worrying. According to the U.S. Fire Service, more than 700 wildfires occur every year, burning down approximately 7 million acres of land and destroying more than 26,000 structures. The U.S. government spends over 5 billion dollars each year to fight these uncontrollable monster fires, yet the correct prediction and management of wildfires still remain elusive.    

#### Wildfires in the U.S.   
Here are some facts about wildfires in the U.S.     

* Cause   
According to the U.S. Department of Interior, about 90 percent of wildfires in the United States are started by human, resulting from unattended campfires, debris burnings, downed electrical equipments and power lines, negligently discarded cigarettes and intentional acts of arson, etc. Verisk's 2017 Wildfire Risk Analysis shows that at present, 4.5 million U.S. homes are identified as having high or extreme high risk of wildfire, where more than 2 million homes are in California. The nature (lightning or lava) and climate change, are found to be responsible for the remaining 10 percent.   

* Loss     
In October 2019, significant fires broke out in California and led to the evacuation of over 200,000 people, which were declared as a state of emergency. The Kincade Fire in Sonoma County burned over 76,000 acres. The Getty Fire in Los Angeles caused over 7000 residences to be placed in a mandatory evacuation zone.    

  In 2018, there were 58,083 wildfires where 8.8 million acres were burned.   

  In 2017, there were 71,499 wildfires where over 10 million acres were burned.   

* Policy   
The governmental strategy on wildfires has undergone a major shift from the primary focus on suppression of wildfires to multiple, comprehensive measures with sustainable potential. Current policies aim to help manage wildfire risk by reduction of hazardous fuels, restoration of the ecosystem and assistance from the communities, etc. For instance, the federal government have formulated and implemented policies on protecting funds dedicated to forest management and resotration, as well as expediting small-scale forest management research projects.   

#### Goals of our Project
Considering these massive, devastating wildfires and their catastropic effects on human communities and the environment, we decide to investigate the following research questions to discover if there is any clear trend and to learn how to better prevent and control wildfires. We also build a linear regression model to assess the relationship between fire duration and some potential risk factors. In this project, we are going to examine:    

* The frequency of wildfires across states over time from 2005 to 2015 and the top ten states with the largest number of wildfires in the ten-year period      

* The geographical distribution of wildfires across states with the number of wildfires per squre mile    

* The most common causes of wildfires       

* The relationship between duration and fire size   

* The association among a number of factors and the duration of wildfires in Riverside, California and Dallas, Texas  

## **Initial Questions**
At first, we were interested in exploring the correlation between wildfire's occurence/ severity and a number of factors, such as location, time, weather and so on. Particularly, we wanted to find out if there is a predictive model that can be used to fit our data. However, because the information of our dataset is quite limited (with many missing values and some wrong values), we failed to provide such a model with high accuracy and precision regarding the wildfire's occurence/severity at a national level. As a result, we ended up with two counties - Riverside, California and Dallas, Texas, which had the highest number of the most destructive wildfires in year 2015, and attempted to build a regression model to examine the association between the duration of wildfires along with other factors like weather, size and cause. Despite the fact that we narrowed down the scope of our research in terms of predicting wildfires, we have finished all the exploratory data analysis as we proposed at the beginning of this project.  

## **Data**

* **`state` and `county` datasets in package `ggplot2`**

  The `state` and `county` dataset are used to plot the map in exploratory analysis and shiny apps.

* **`state.x77` dataset**

  We use `Area` variable to calculate the number of wildfires per square mile
  
* **NOAA Weather Data**

  We use this data to find the association among duration, number of fires and tempreture in riverside, California.

* **1.88 Million US Wildfire. 24 years of geo-referenced wildfire records**

  This data publication contains a spatial database of wildfires that occurred in the United States from 1992 to 2015. This dataset includes 1.88 million geo-referenced wildfire records, representing a total of 140 million acres burned during the 24-year period. We mainly focus on the time period from 2005 to 2015 and the following core data elements: discovery and control date, final fire size, causes of wildfires and a point location.

  The variables we used for analysis are: 

  + `duration` = Burning time in hours calculated by `discovery_date`, `discovery_time`, `cont_data` and `cont_time`.

  + `FIRE_SIZE_CLASS` = Code for fire size based on the number of acres within the final fire perimeter expenditures (A=greater than 0 but less than or equal to 0.25 acres, B=0.26-9.9 acres, C=10.0-99.9 acres, D=100-299 acres, E=300 to 999 acres, F=1000 to 4999 acres, and G=5000+ acres).

  + `STAT_CAUSE_DESCR` = Description of the cause of the fire.

## **Exploratory Analysis**

## **Statistical Analysis**

## **Discussion**
We recognize that wildfires have various causes and the severity (size, duration...) of wildfires differ by a number of factors; thus, the co


As climate change continues to intensify wildfires, it is everyone's responbility to understand and learn how to prevent wildfires from happening and protect nature and ourselves. Futhermore, we shall continue our quest to correctly and timely predict future wildfires, using extensive dataset with advanced predictive modelling techniques. 

