---
title: "Statistical Analysis"

output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include = FALSE}
library(tidyverse)
library(rnoaa)
library(viridis)
```

```{r prepare the data, message = FALSE, warning = FALSE}
fire = read_csv("./final_report/data/fire_0515.csv")

state.abb = append(state.abb, c("DC", "PR"))
state.name = append(state.name, c("District of Columbia", "Puerto Rico"))

tidy_fire = 
  fire %>% 
  separate(cont_time, into = c("cont_hour","cont_min") ,sep = 2) %>% 
  separate(discovery_time, into = c("disc_hour","disc_min") ,sep = 2) %>% 
  mutate(cont_hour = as.numeric(cont_hour),
         cont_min = as.numeric(cont_min),
         disc_hour = as.numeric(disc_hour),
         disc_min = as.numeric(disc_min)) %>% 
  # change julian days
  mutate(discovery_date = as.Date(discovery_date - 2458014.5, origin = '2017-09-18'),
         cont_date = as.Date(cont_date - 2458014.5, origin = '2017-09-18'),
         duration_day = as.numeric(difftime(cont_date, discovery_date, units = "days"))) %>% 
  mutate(
    duration_hour = cont_hour - disc_hour,
    duration_min = cont_min - disc_min,
    duration = duration_day * 24 + duration_hour + duration_min / 60
  ) %>% 
  select(-duration_day, -duration_hour,-duration_min) %>% 
  mutate(fips_name = tolower(fips_name),
         state = fct_inorder(state),
         fire_size_class = fct_inorder(fire_size_class),
         region = state.name[match(state, state.abb)],
         cause = as.factor(stat_cause_descr),
         cause = relevel(cause, ref = "Missing/Undefined"))
```

## Association between cause and size of fire

```{r}
model_1 = lm(fire_size ~ duration + stat_cause_descr, data = tidy_fire)
summary(model_1)


```

## Association between temperature and the number of fires

```{r, message = FALSE, warning = FALSE}
fire_15 = tidy_fire %>% 
  filter(state == "CA" | state == "TX") %>% 
  filter(fire_year == 2015) %>% 
  drop_na(fips_code, fips_name)

fire_15 %>% 
  group_by(region, fips_name) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  group_by(region) %>% 
  mutate(rank = rank(-n)) %>% 
  filter(rank == 1) %>% 
  select(-rank)

stations = ghcnd_stations()

stations_15 = stations %>% 
  mutate(name = tolower(name)) %>% 
  filter(state == "CA" | state == "TX") %>% 
  filter(str_detect(name, c("riverside", "dallas")),
         last_year == 2019, 
         element == "TMAX")

station_id = pull(stations_15, id)

weather_15 = meteo_pull_monitors(station_id,
                                  date_min = "2015-01-01", 
                                  date_max = "2015-12-31",
                                  var = c("PRCP", "TMAX", "TMIN")) %>% 
  mutate(tmax = tmax / 10,
         tmin = tmin / 10,
         tmean = (tmax + tmin) / 2,
         fips_name = recode(id, 
                            "USW00003171" = "riverside",
                            "USW00013960" = "dallas"))

fire_15 = fire_15 %>% 
  filter(fips_name == "riverside" | fips_name == "dallas") %>% 
  mutate(date = discovery_date)

fire_15_weather = left_join(fire_15, weather_15, by = c("date", "fips_name"))

fire_15_weather %>% 
  ggplot(aes(x = date, group = fips_name, color = fips_name)) +
  geom_point(aes(y = tmean, size = prcp), alpha = .8)

fire_15_weather %>% 
  group_by(date, fips_name) %>% 
  ggplot(aes(x = date, fill = fips_name)) + 
  geom_histogram(alpha = 0.8) +
  scale_color_viridis()

fire_15_count = fire_15_weather %>% 
  group_by(date, tmean, prcp, stat_cause_descr) %>% 
  summarise(n = n())


```









