---
title: "heatmap"
author: "Mengyu Zhang"
date: "12/2/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(viridis)
library(ggExtra)
library(plotly)
```
## Data Clean
```{r}
fire = 
  read_csv("data/fire_0515.csv") %>% 
  mutate(date = as.Date(discovery_date - 2458014.5, origin = '2017-09-18'),
         cont_dateymd = as.Date(cont_date - 2458014.5, origin = '2017-09-18')) %>% # change julian days
  separate(date, into = c('year', 'month', 'day'), sep = "-") %>% 
  mutate(month = month.abb[as.numeric(month)],
         month = fct_rev(factor(month, levels = month.abb)))
```

##

```{r}
plot_df = fire %>%
  group_by(year, month, day) %>% 
  summarise(n_fires = n()) %>% 
  mutate(day = as.numeric(day))
 
plot = plot_df %>% 
  ggplot(aes(x = day, y = month, fill = n_fires))+
  geom_tile(color = "white",size = 0.1) + 
  scale_fill_viridis(name = "Number of Wildfires",option = "C") + 
  facet_grid(.~ year) +
  scale_x_continuous(breaks = c(1,10,20,31)) + 
  theme_minimal(base_size = 8) + 
  labs(title = "Number of Wildfires from 2005 to 2015", x = "Day", y = "Month") + 
  theme(legend.position = "bottom")+
  theme(plot.title = element_text(size = 14))+
  theme(axis.text.y = element_text(size = 6)) +
  theme(strip.background = element_rect(colour = "white"))+
  theme(plot.title = element_text(hjust = 0))+
  theme(axis.ticks = element_blank())+
  theme(axis.text = element_text(size = 7))+
  theme(legend.title = element_text(size = 8))+
  theme(legend.text = element_text(size = 6))+
  removeGrid()

ggplotly(plot + theme(legend.position = "none"))

```

