---
title: "proposal"
date: 12/02/2019
output: html_document
---

## Group Member

  * Sitong Cui (sc4636)
  * Jiarui Fu (jf3285) 
  * Mengyuan Li (ml4418)
  * Mengyu Zhang (mz2777)
  * Ziqi Zhou (zz2710)


## Project Title

Topic: 2005-2015 US Wildfires 

## Motivation

Wildfire is dangerous and needs people’s enough attention because of its uncontrollability and destructive effects. At every year, wildfire leads to big financial loss and kills many lives. Moreover, the environment pollution due to wildfire is far more severe than wildfire itself. If there is any approach that helps us effectively prevent wildfires, then we can save our lives and avoid many big losses and destructions. 

Based on the purpose of effectively preventing wildfires, our group work on the dataset, “1.88 Million US Wildfires-24 years of geo-referenced wildfire records”, and try to discover some potential trends of wildfires. 


***



## Intended Final Product

shiny APP which can show deographical distribution (maps) of wildfires in US from 2009 to 2015, and in both 2010 and 2015. 


***



## Planned Analysis

* The distributions of wildfire occurring frenquency in the U.S.
* The relationship between the wildfire occurring frequency and time or location.
* The relationship between the fire size and the time or location.



## Anticipated Data Sources

* 1.88 Million US Wildfires.24 years of geo-referenced wildfire records [here](https://www.kaggle.com/rtatman/188-million-us-wildfires)


## Challenges
* big dataset
* hard to calculate wildfire duration
* difficulty of building websites

***


### Planned Analysis
* Which state has most wildfires
* Which state has biggest wildfire
* Is there any relationship between wildfire size and duration

### Visualizations
* ridge plot, bubble plot, density polt, etc.  
* The map showing the wildfire annual distribution in the U.S.

***

## Planned Timeline

| Scheduled Tasks                   | Due dates                 |
| --------------------------------- | ------------------------- |
| Scrape data and tidy              | Nov. 15 (Friday)          |
| Analyse and produce visualization | Nov. 22 (Friday)          |
| Draft report                      | Nov. 29 (Friday)          |
| Make webpage and screencast       | Dec. 3  (Tuesday)         |
| Final editing                     | Dec. 4  (Wednesday)       |









